### ISSUE TITLE
Bla Bla nr. 1

### ISSUE THREAD

**Issue by safetychangerzen** [changer/changer.github.com#107]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [34](https://safetychanger.zendesk.com/agent/#/tickets/34)
**Priority:** normal
**Zendesk assignee:** development/Development
 **Issue Type:** feature
 **Feature score:** 

**Original ticket content:**

Hello, 

I have a new idea: 

Bla bla

**Comment by safetychangerzen** [comment]
*Comment from Zendesk by michiel.potter@potterim.nl at 2015-03-13 09:15:30 UTC:*

<p>Hello, </p>

<p>I have a new idea: </p>

<p>Bla bla</p>

**Comment by safetychangerzen** [comment]
*Comment from Zendesk by support1@safetychanger.com at 2015-03-13 09:33:19 UTC:*

<p>Describes feature please investigate.</p>

**Comment by aderjaan** [comment]
close, some playing with zendesk
