### ISSUE TITLE
Get an untranslated error without help

### ISSUE THREAD

**Issue by safetychangerzen** [changer/changer.github.com#109]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [91](https://safetychanger.zendesk.com/agent/#/tickets/91)
**Priority:** low
**Zendesk assignee:** N/A
 **Issue Type:** 
 **Feature score:** 

**Original ticket content:**

.:Environment:.
Device: Huawei G6-L11
OS: Android 4.3
App: IncidentChanger (Hockeyapp) 1.0.20 20 feb

.:Steps taken:.
1. Started IC app.
2. Get a 'Unauthorized' error.

.:Expected result:.
See it in Dutch (because al the text is in dutch).
Get a tip how to fix this like: Logout and try to login again.

.:Actual result:.
Has to figure out by myself how to fix this.

.:Priority:.
Low

**Comment by safetychangerzen** [comment]
*Comment from Zendesk by testing@changer.nl at 2015-03-24 15:43:13 UTC:*

<p>.:Environment:.
<br />Device: Huawei G6-L11
<br />OS: Android 4.3
<br />App: IncidentChanger (Hockeyapp) 1.0.20 20 feb</p>

<p>.:Steps taken:.
<br />1. Started IC app.
<br />2. Get a &#39;Unauthorized&#39; error.</p>

<p>.:Expected result:.
<br />See it in Dutch (because al the text is in dutch).
<br />Get a tip how to fix this like: Logout and try to login again.</p>

<p>.:Actual result:.
<br />Has to figure out by myself how to fix this.</p>

<p>.:Priority:.
<br />Low</p>

**Comment by aderjaan** [comment]
closed, was not meant to be
